### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by JeromeBKK** [eisenjulian/fb-page-chat-download#2]
Hi,

First of all thanks for the script.

I have no knowledge about Python but I'm managed to run your script under windows.

Unfortunately, I got the error below:

_Traceback (most recent call last):
  File "fb-page-chat-download/run.py", line 15, in <module>
    import requests
ImportError: No module named requests_

Regards.

**Comment by eisenjulian** [comment]
Hello there, can you try `$ pip install requests`?

**Comment by JeromeBKK** [comment]
It works but now I have another error with the unidecode module 🤔

**Comment by eisenjulian** [comment]
Can you paste the stack trace?

**Comment by JeromeBKK** [comment]
I don't know how to do that but here is the error:

_Traceback (most recent call last):
  File "fb-page-chat-download/run.py", line 20, in <module>
    import unidecode
ImportError: No module named unidecode_

**Comment by JeromeBKK** [comment]
I managed to install the unidecode module.

Here is the last update ;)

![image](https://user-images.githubusercontent.com/31691187/30144781-87b348fc-93b7-11e7-9158-5e8a8ba35a6d.png)

**Comment by eisenjulian** [comment]
The issue is that the code was intended to be run in python 3, not python 2, however you might be able to successfully run the script either:
 a) replace `open(self.output, 'w', newsline ....` by `open(self.output, 'w')`
or 
 b) add `from io import open` at the top of the file

Sorry for inconvenience, good luck! BTW I found data on your issue here https://stackoverflow.com/questions/42181907/typeerror-file-takes-at-most-3-arguments-4-given
